version: '3.8'

services:
  tourist-db:
    container_name: tourist-db
    build:
      context: ./
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  tourist-api:
    container_name: tourist-api
    image: nmngo248/tourist-api:latest
    build:
      context: ./
      dockerfile: api.Dockerfile
    depends_on:
      - tourist-db
    env_file:
      - .env
    ports:
      - "8000:5000"

volumes:
  db-data:

