FROM openjdk:11-jdk
VOLUME /tmp
ARG JAR_FILE=target/*.jar

ENV API_GOOGLE_KEY=$API_GOOGLE_KEY
ENV CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
ENV CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
ENV JWT_CONFIG_SECRET_KEY=$JWT_CONFIG_SECRET_KEY
ENV JWT_CONFIG_TIME_EXPIRATION=$JWT_CONFIG_TIME_EXPIRATION
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD

COPY ${JAR_FILE} app.jar
COPY ./config-db.sh /config-db.sh

RUN chmod +x /config-db.sh
CMD ["/config-db.sh"]
ENTRYPOINT ["java","-jar","/app.jar"]
