spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jackson:
    time-zone: GMT+7
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 115MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
    tomcat:
      connection-properties: useUnicode=true
      characterEncoding: utf-8
  data:
    cassandra:
      schema-action: create_if_not_exists
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework:
        web: TRACE
cloudinary:
  max-file-size: 20MB
  max-image-width: 5000
