spring:
  jackson:
    time-zone: GMT+1
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
  tomcat:
    connection-properties: useUnicode=true
    characterEncoding: utf-8
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQLDialect
  cassandra:
    schema-action: create_if_not_exists

server:
  error:
    include-message: always
